# blue-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue-deployment
  annotations:
    kubernetes.io/change-cause: "Initail Demo application"
    kubernetes.io/description: "Rolling Demo application"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  strategy:
  # availableReplicas = replicas - maxUnavailable < availableReplicas < replicas + maxSurge
    rollingUpdate:
      maxSurge: 2 # 롤링 업데이트 중 동시에 생성하는 파드 갯수(default: 25%)
      maxUnavailable: 0 # 롤링 업데이트 중 동시에 삭제할 수 있는 파드 갯수(default: 25%)
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: nationminu/blue:v1
        name: blue
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /version.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3